apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx1
  name: nginx1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx1
  strategy: {}
  template:
    metadata:
      labels:
        app: nginx1
    spec:
      containers:
      - image: harbor.tkg.io/library/docker-example:33
        name: docker-example
        resources: {}
status: {}

